service: boomshrug
runtime: python
env: flex
entrypoint: gunicon -b :$PORT boomshrug:app

runtime_config:
  python_version: 3

env_variables:
  TEAM_ID: blank
  HOOKURL: blank
  TOKEN: blank

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
